apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        image: getricecrispy/my-vite-app:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: vite-app-service
spec:
  type: LoadBalancer
  selector:
    app: vite-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
